import 'dotenv/config';
import type { WalletsConfig } from '../types/wallet.types';
import { Converter } from '../utils/unit_converts';

const NODES_API_KEY = process.env.NODES_API_KEY || '';

const main: WalletsConfig = {
  XNO: {
    mainAccountHot: 'nano_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/XNO',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=XNO&api=${NODES_API_KEY}`],
    converter: new Converter('XNO'),
    name: 'Nano',
    decimalsToShow: 8,
    prefix: 'nano',
    logo: 'https://nanswap.com/logo/XNO.svg',
    explorer: 'https://nanolooker.com/block/',
    maxBet: 130,
  },
  XRO: {
    mainAccountHot: 'xro_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/XRO',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=XRO&api=${NODES_API_KEY}`],
    converter: new Converter('XRO'),
    name: 'RaiBlocksOne',
    decimalsToShow: 8,
    prefix: 'xro',
    logo: 'https://nanswap.com/logo/XNO.svg',
    explorer: 'https://nanolooker.com/block/',
    maxBet: 867398,
  },
  BAN: {
    mainAccountHot: 'ban_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/BAN',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=BAN&api=${NODES_API_KEY}`],
    converter: new Converter('BAN'),
    name: 'Banano',
    decimalsToShow: 8,
    prefix: 'ban',
    logo: 'https://nanswap.com/logo/BAN.svg',
    explorer: 'https://bananolooker.com/block/',
    maxBet: 90000,
  },
  XDG: {
    mainAccountHot: 'xdg_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/XDG',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=XDG&api=${NODES_API_KEY}`],
    converter: new Converter('XDG'),
    name: 'DogeNano',
    decimalsToShow: 8,
    prefix: 'xdg',
    logo: 'https://nanswap.com/logo/XDG.png',
    explorer: 'https://explorer.dogenano.io/block/',
    maxBet: 28352,
  },
  ANA: {
    mainAccountHot: 'ana_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/ANA',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=ANA&api=${NODES_API_KEY}`],
    converter: new Converter('ANA'),
    name: 'Ananos',
    decimalsToShow: 8,
    prefix: 'ana',
    logo: 'https://nanswap.com/logo/ANA.png',
    explorer: 'https://ananault.lightcord.org/transaction/',
    maxBet: 53862940,
  },
  NANUSD: {
    mainAccountHot: 'usd_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/NANUSD',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=NANUSD&api=${NODES_API_KEY}`],
    converter: new Converter('NANUSD'),
    name: 'nanUSD',
    decimalsToShow: 6,
    prefix: 'usd',
    logo: 'https://nanswap.com/logo/NANUSD.svg',
    explorer: 'https://nanolooker.com/block/',
    maxBet: 100,
  },
  NANBTC: {
    mainAccountHot: 'nanbtc_13nbbqp5bxaxzw7n5ctqxr9q54dfj7q56u9yjmhhtb3reu6cfzyjkyho4a4n',
    RPC: 'https://nodes.nanswap.com/NANBTC',
    WS: [`wss://nodes.nanswap.com/ws/?ticker=NANBTC&api=${NODES_API_KEY}`],
    converter: new Converter('NANBTC'),
    name: 'nanBTC',
    decimalsToShow: 8,
    prefix: 'nanbtc',
    logo: 'https://bucket.nanwallet.com/logo/BTC.svg',
    explorer: 'https://nanolooker.com/block/',
    maxBet: 0.01,
  },
};

export default main;
